### ISSUE TITLE
和另一个库Unity-Logs-Viewer很类似？

### ISSUE THREAD

**Issue by zhaoqingqing** [luzexi/Unity3DRuntimeDebug#2]
我在项目也在使用这个来查看日志，但我是在另一个github上下载的： [https://github.com/aliessmael/Unity-Logs-Viewer/](https://github.com/aliessmael/Unity-Logs-Viewer/)

我对比了这两个库的核心代码很类似，你这个库比那个库的创建时间更早。

**Comment by luzexi** [comment]
这个库好像是官方的免费的我记得，只是我用的比较勤，懒得去assetstore上找，就放上来了，顺便加了个静态接口用起来顺手点。

**Comment by zhaoqingqing** [comment]
:smiley: 了解
